# Generated by Django 4.1.2 on 2022-10-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
